ALTER TABLE presupuesto
    ADD COLUMN IF NOT EXISTS sena_preference_id VARCHAR(100),
    ADD COLUMN IF NOT EXISTS sena_monto NUMERIC(12,2),
    ADD COLUMN IF NOT EXISTS sena_estado VARCHAR(20) DEFAULT 'PENDIENTE'
    CHECK (sena_estado IN ('PENDIENTE','ACREDITADA','CANCELADA'));