ALTER TABLE pago_manual
    ADD COLUMN IF NOT EXISTS referencia   VARCHAR(100),
    ADD COLUMN IF NOT EXISTS fecha_pago   TIMESTAMP NOT NULL DEFAULT now(),
    ADD COLUMN IF NOT EXISTS usuario      VARCHAR(80),
    ADD COLUMN IF NOT EXISTS nota         TEXT,
    ADD COLUMN IF NOT EXISTS created_at   TIMESTAMP NOT NULL DEFAULT now();